### PR TITLE
MAINTAINERS: add more pizza

### PR DESCRIPTION
**Pull request by tych0**
My e-mail address has changed, let's change it here too. Pizza is tasty.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM. :+1: for 24-hour pizza.

**Comment by tych0** [comment]
Looks like CI is pretty sad about pizza though :(

**Comment by cyphar** [comment]
Yeah CI is quite broken. Seems something is wrong with the openSUSE bats package. Lemme take a look...

**Comment by cyphar** [comment]
It was an upstream regression, I've backported the fix to openSUSE so it should be fixed now.

**Pull request closed without merging**
