### PR TITLE
*: update to reflect inclusion into OCI

### PR DESCRIPTION
**Pull request by cyphar**
The key changes here are:

 * Add @vbatts as a maintainer.
 * Restructure all of the governance documents to match the new ones described in the OCI proposal.
 * Rename all references to `openSUSE` (most notably in import paths) to `opencontainers`.
 * Update the website, including a merging of the `README.md` and the website home-page (among other changes).

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
Technically I can still LGTM this one myself, but in order to make this formal let's do it by unanimous vote of all maintainers. @tych0 can you please take a look at this?

**Comment by tych0** [comment]
LGTM

**Comment by cyphar** [comment]
https://lgtm.cyphar.com/ doesn't like the new opencontainers home. We might have to switch away from it, but for now I'll just remove it as being required.

**Comment by tych0** [comment]
In that case, I approve ;)

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
