### PR TITLE
chore: Update dependencies to latest for CVEs

### PR DESCRIPTION
**Pull request by blkperl**

### CODE REVIEW

**Comment by blkperl** [comment]
@cyphar any tips on the test failures?

**Comment by cyphar** [comment]
I'm working on the test failures. I started trying to fix them a few months ago but a bunch of other stuff got in the way. :sweat_smile:

**Comment by cyphar** [comment]
There are two test failure issues. One is the lint one (working on that), the other is with this PR -- the updated vendor of the `https://github.com/rootless-containers/proto` contains a package with more than one Go `package ...` in it. I suspect there's something odd about what `go mod vendor` is doing...

**Comment by cyphar** [comment]
Closing in favour of #470. Thanks for sending a PR though!

**Pull request closed without merging**
